# Generated by Django 5.0.3 on 2024-03-18 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forums', '0001_initial'),
        ('media', '0001_initial'),
        ('shops', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('id_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
                ('id_forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.forum')),
                ('media', models.ManyToManyField(to='media.media')),
            ],
        ),
    ]
