# Generated by Django 5.0.3 on 2024-04-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_id_alter_media_url'),
        ('posts', '0004_remove_post_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ManyToManyField(blank=True, to='media.media'),
        ),
    ]
