# Generated by Django 5.0.3 on 2024-04-10 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0011_alter_forum_image'),
        ('posts', '0005_post_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forums.forum'),
            preserve_default=False,
        ),
    ]
