# Generated by Django 5.0.3 on 2024-04-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_id_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_forum',
        ),
    ]
