POST http://127.0.0.1:8000/accounts/register/
Content-Type: application/json
Authorization: token 44d39786cca1a13c89432a6ea0db14f54d5e6780

{ "username": "perona", "password": "1234"}

###

POST http://127.0.0.1:8000/accounts/login/ 
Content-Type: application/json

{ "username": "admin", "password": "admin" }

###

GET http://127.0.0.1:8000/accounts/test/
Content-Type: application/json
Authorization: token c02d7f8af8e252f5ec69cba2f9c76b8be62fd20d

###

POST http://127.0.0.1:8000/accounts/vvv/changepassword/
Content-Type: application/json
Authorization: token 9ed6c1788659b78dfdece859d302fbefc78370e7

{ "username": "test", "password": "1234" }