POST http://127.0.0.1:8000/forums/7/posts/27/comments/
Content-Type: application/json
Authorization: token c9b638f0f902cfe2a25d057fad309c721f975c78

{
    "content": "Comment example"
}

###

GET http://127.0.0.1:8000/forums/7/posts/55/comments/?page=1
Content-Type: application/json
Authorization: token 44d39786cca1a13c89432a6ea0db14f54d5e6780

###

DELETE http://127.0.0.1:8000/comments/3/
Content-Type: application/json
Authorization: token 48d2d139f6da2cb8ccb433799639ec2f157dc6cd
