GET http://127.0.0.1:8000/forums/all
Content-Type: application/json

###

GET http://127.0.0.1:8000/forums/1
Content-Type: application/json

###

POST http://127.0.0.1:8000/forums/
Content-Type: application/json

{
    "title": "test",
    "date": "test",
    "body": "test",
    "media": ["test1.jpg", "test2.jpg"],
    "id_creator": 1
}
