GET http://127.0.0.1:8000/forums/all/
Content-Type: application/json

###

GET http://127.0.0.1:8000/forums/1/
Content-Type: application/json

###

POST http://127.0.0.1:8000/forums/
Content-Type: application/json

{
    "title": "test",
    "read_members": "test",
    "read_write_members": ["test1.jpg", "test2.jpg"],
}
