"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import firebase_admin
from firebase_admin import credentials

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&p)fujjsnfunfr4ahx*z(wz^#5b#8aq1to!w14sf!@4zfjb3l&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

APPEND_SLASH=False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'fcm_django',
    'media',
    'shops',
    'forums',
    'posts',
    'accounts',
]

AUTH_USER_MODEL = 'accounts.Account'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Initialize Firebase SDK with service account credentials
cred = credentials.Certificate("./server/firebase/app-merchants-association-firebase-adminsdk-79gh2-ecbf1f1a3f.json")
firebase_admin.initialize_app(cred)

# FIREBASE FCM
{
  "type": "service_account",
  "project_id": "app-merchants-association",

  "private_key_id": "ecbf1f1a3f044acb7c3ccfcc7a7b9cb0d906c503",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCsvKdppy35Z0bs\nmafrx+/ltwoktBae1ujtJPol/crYxHRvZ2okQT1npBb+GrM7mX3iWzF1kKfzl2mT\nIvb53AOq4PTVAqQvf2P+ygG84rNGpFh+jX1zhL+NzkCSM9RtSBWVGeujwmNUaXkI\n2XyIgUBmSxFqj7PBFjeC1U/H1iXiHcGPGK7+y05SyKE0Buxibg8s5Fkxzh1o6Was\nRIf9zIE2qr0RZpA60cB/IQixttD60bX403Yue7e5WUN4oryJrGVprCTdP06tYRi3\n5li2chvAe4XisYbkcKIkEeE5D7YzvAs7e4N+dgPXYAGPxYTRqEd0+v7wk9Fa4poK\nB7rUidB9AgMBAAECggEACffvfmFQ6HrNZO6Uz6klFEqXpINwZxVrxvG9GOUC/YxQ\nKYoG3gBA1lgUdptyWqm9PMtP+PhSj57I5N5Im/tBNULlsNxF6YgjwcAFJnzRD+4r\nPY8V8rfHY9wyWELy9aU1D6V5to82Mxh3d8CwrI0EUH2btpyuk4xKwvtjRFr8qoY+\nLnB5ZrIz8gNLRa4wIjVZEKgO0km8E9DiUp2wu4pDytjYLgTjmOBn6V6OXslzcYas\nRefwtmNicXtT3gruXjbmpjNWihUUU7ucXDrCan9p/CqPPbdsgGkv6EI1Sc/on3O1\nQoef0lWHQT3yhlUUIjZGZXWZC5C0qdyzSMmlh58xYQKBgQDpayekSnjdbIOxHjO0\nU0R2qImCFey5L42PVRM3rh5f7+9ke2DImoCDVFMJx3gqDsf88M9iW0gNauei2e//\nyVMADL/qWwlDuPfiFNjXi9AzL32rVTZvGMWm3LIMZLCnsZxD4bpFi5G5LMovOKZL\nTtgOE4hIlvJfGvwZMB90XVKL4QKBgQC9cqhFhNxBLSrGMx0pzoWpGaSJXm+ifkGK\ncpDTUmS9Y9yvnP7RKGibAMXbZqTeAo2aX/HOGIqJZwNVye+chD87jx0sSGAVONvN\nWqWsWzoJlMjk/G6hGvfQSLEr9YIJ4wNudfLsZj3UpWS5do+9mEmtLxD+ZHo+zuCF\nHceyMG74HQKBgQDc2JSmPgwDPCORlgjHia0SM73+xa23PQXL4muPV//HN6WhxZY5\n1uzW1RbH/uFzsY6IhHNDFSikAUzuaRNJSPtt5aJDIyUt3TkzwBO2RMOVWk6lp7cc\nAC0qBk+zqCT4VPSLyWvLVxVmRbl6WjgEsrF7CAH+5Eqnr0lsr3pjR9TNIQKBgC96\nFIGXkjsjPpz9Iknf389JBdsHN6LZUUOJApJzC5wK8rtv9Mwl/FEcGHmrd5XLvgD6\nGncz30Qf9M4DFXF8EvyyGPWIDcxDu5HzLaHMGvdbuhzoxjDJuWERVpVVqYkgwzNj\ni8WCuewYpu1zsQIqsAwex3t5YslqvwmdNPaK/MRhAoGAP9dcJSKpc48w8VX/f57Z\nz1LLUMYT3sJj2gggv8NOVVV0+cHagXORKIf5UYrjhdyRb/1lrWmu4CrpBmjD7N7p\nyXbN2RfPyxxYuV13VivhxTiJGYF0yhaFuImgMp9GjLgCpWAa0AGQnwmXkgQbW5su\ntSmWJOqV/gwMfCOxragFpCk=\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-79gh2@app-merchants-association.iam.gserviceaccount.com",
  "client_id": "103264586301125714419",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-79gh2%40app-merchants-association.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}

FCM_DJANGO_SETTINGS = {
     # an instance of firebase_admin.App to be used as default for all fcm-django requests
     # default: None (the default Firebase app)
    "DEFAULT_FIREBASE_APP": None,
     # default: _('FCM Django')
    "APP_VERBOSE_NAME": "[string for AppConfig's verbose_name]",
     # true if you want to have only one active device per registered user at a time
     # default: False
    "ONE_DEVICE_PER_USER": True,
     # devices to which notifications cannot be sent,
     # are deleted upon receiving error response from FCM
     # default: False
    "DELETE_INACTIVE_DEVICES": False,
}