# Generated by Django 5.0.3 on 2024-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_remove_shop_owner_shop_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='sector',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
