# Generated by Django 5.0.3 on 2024-04-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_shop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='image',
        ),
    ]
