# Generated by Django 5.0.3 on 2024-04-13 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_remove_media_image_alter_media_id'),
        ('shops', '0005_remove_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='media.media'),
            preserve_default=False,
        ),
    ]
