# Generated by Django 5.0.3 on 2024-04-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_alter_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='facebook',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='instagram',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='webpage',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
