# Generated by Django 5.0.3 on 2024-04-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_shop_facebook_shop_instagram_shop_webpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='webpage',
            field=models.URLField(blank=True),
        ),
    ]
