# Generated by Django 5.0.3 on 2024-04-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_alter_shop_facebook_alter_shop_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='sector',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
