# Generated by Django 5.0.3 on 2024-04-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_alter_shop_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='facebook',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='shop',
            name='instagram',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='shop',
            name='webpage',
            field=models.URLField(blank=True, default=None),
        ),
    ]
