# Generated by Django 5.0.3 on 2024-04-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_alter_shop_facebook_alter_shop_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='facebook',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='instagram',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='webpage',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
