# Generated by Django 5.0.3 on 2024-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_alter_shop_facebook_alter_shop_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='mail',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
