# Generated by Django 5.0.3 on 2024-04-04 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='posts',
            field=models.ManyToManyField(to='posts.post'),
        ),
    ]
