# Generated by Django 5.0.3 on 2024-04-10 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_alter_forum_posts'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.media'),
        ),
    ]
