# Generated by Django 5.0.3 on 2024-04-13 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0011_alter_forum_image'),
        ('media', '0005_remove_media_image_alter_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='media.media'),
        ),
    ]
