# Generated by Django 5.0.3 on 2024-04-15 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0013_remove_forum_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
