# Generated by Django 5.0.4 on 2024-05-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0014_alter_forum_date'),
        ('shops', '0014_shop_bio_shop_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='read_members',
            field=models.ManyToManyField(blank=True, related_name='read_members', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='read_write_members',
            field=models.ManyToManyField(blank=True, related_name='read_write_members', to='shops.shop'),
        ),
    ]
