# Generated by Django 5.0.3 on 2024-04-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='id',
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
