# Generated by Django 5.0.3 on 2024-04-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_media_id_alter_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
