# Generated by Django 5.0.3 on 2024-04-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_id_alter_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
